version: "3"

services:
  mysql-db:
    build: ./mysql
    environment:
      MYSQL_DATABASE: project_vodan
      MYSQL_ROOT_PASSWORD: abc123
    ports:
      - 3306:3306
    volumes:
      - ./mysql-db-store/:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.9
    environment:
      PMA_HOST: mysql-db
    ports:
      - 8080:80
    depends_on:
      - mysql-db
